server:
  port: 8041

spring:
  application:
    name: eureka-producer

eureka:
  instance:
    instance-id: eureka-producer:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8040/eureka/